--Procedimientos almacenados
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   FUNCTION [dbo].[OBTENER_FECHA] ()
RETURNS DATETIME
AS
BEGIN
    --RETURN GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Central Standard Time'
    --RETURN GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Pacific Standard Time'
    RETURN CAST(CAST(GETUTCDATE() AS DATETIMEOFFSET) AT TIME ZONE 'CENTRAL STANDARD TIME (MEXICO)' AS DATETIME)
END
GO

--Dar de alta a un participante.
GO
CREATE OR ALTER PROCEDURE ALTA_ALUMNO(@CORREO VARCHAR(100),@CONTRASENA VARCHAR(50),@CELULAR VARCHAR(16),@FECHA_NAC DATE,@NOMBRE VARCHAR(50),@AP_P VARCHAR(50),@AP_M VARCHAR(50),
@ID_ESCUELA INT)
AS
	INSERT INTO USUARIO(FECHA_REGISTRO) VALUES()	

END
SELECT DBO.OBTENER_FECHA()