CREATE DATABASE SIEMBRA_VALORES;
USE SIEMBRA_VALORES;

-- Tabla Colonia
CREATE TABLE COLONIA (
    ID_COL INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100),
    CIUDAD VARCHAR(100),
    COD_POSTAL VARCHAR(10),
	FECHA_REGISTRO DATETIME,
	ACTIVO BIT DEFAULT 1,
    META INT,
    MINIMO_ARBOLES INT
);

-- Tabla Usuario
CREATE TABLE USUARIO (
    ID_US INT PRIMARY KEY IDENTITY(1,1),
    FECHA_REGISTRO DATETIME,
    NOMBRE VARCHAR(50),
    AP_P VARCHAR(50),
    AP_M VARCHAR(50),
    CORREO VARCHAR(100),
    CELULAR VARCHAR(15),
    FECHA_NAC DATE,
    CONTRASENA VARCHAR(50),
    ACTIVO BIT,
    ID_COL INT,
    FOREIGN KEY (ID_COL) REFERENCES COLONIA(ID_COL)
);
-- Tabla Cuidados
CREATE TABLE CUIDADOS (
    ID_CUIDADOS INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100),
    DESCRIPCION TEXT,
    FRECUENCIA VARCHAR(50)
);

-- Tabla Valores
CREATE TABLE VALORES (
    ID_VALOR INT PRIMARY KEY IDENTITY(1,1),
    VALOR VARCHAR(50)
);

-- Tabla Arbol
CREATE TABLE ARBOL (
    ID_ARBOL INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_CIENTIFICO VARCHAR(100),
    FECHA_PLANTADO DATE,
    ENDEMICO BIT,
    ID_VALOR INT,
    ID_CUIDADOS INT,  
	VIVO BIT DEFAULT 1,
	ID_COL INT,
	FECHA_REGISTRO DATETIME,
    FOREIGN KEY (ID_VALOR) REFERENCES VALORES(ID_VALOR),
    FOREIGN KEY (ID_CUIDADOS) REFERENCES CUIDADOS(ID_CUIDADOS),
	FOREIGN KEY (ID_COL) REFERENCES COLONIA(ID_COL)
);
-- Tabla Administrador
CREATE TABLE ADMINISTRADOR (
    ID_US INT PRIMARY KEY,
    ARBOLES_ASIGNADOS INT,
    ULTIMA_CONEXION DATETIME,
    NIVEL VARCHAR(50),
    FOREIGN KEY (ID_US) REFERENCES USUARIO(ID_US)
);

-- Tabla Escuela
CREATE TABLE ESCUELA (
    ID_ESCUELA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(150),
    NIVEL_EDUCATIVO VARCHAR(50),
    NUMERO_ARBOLES INT,
    ENCARGADO VARCHAR(100),
	FECHA_REGISTRO DATETIME,
	ACTIVO BIT DEFAULT 1,
    ID_COL INT,
    FOREIGN KEY (ID_COL) REFERENCES COLONIA(ID_COL)
);

-- Tabla Alumno
CREATE TABLE ALUMNO (
    ID_US INT PRIMARY KEY,
    PUNTOS INT,
	ID_ESCUELA INT,
    FOREIGN KEY (ID_US) REFERENCES USUARIO(ID_US),
	FOREIGN KEY(ID_ESCUELA) REFERENCES ESCUELA(ID_ESCUELA)
);

-- Tabla Adopcion
CREATE TABLE ADOPTA (
    ID_ADOPTA INT PRIMARY KEY IDENTITY(1,1),
    ID_US INT,                -- ID del alumno
    ID_ARBOL INT,            -- ID del �rbol adoptado
    FECHA_ADOPCION_INICIO DATETIME,
    FECHA_ADOPCION_FIN DATETIME,
    ALTURA FLOAT,
    CIRCUNFERENCIA FLOAT,
    FOREIGN KEY (ID_US) REFERENCES ALUMNO(ID_US),
    FOREIGN KEY (ID_ARBOL) REFERENCES ARBOL(ID_ARBOL)
);

-- Tabla Reportes
CREATE TABLE REPORTES (
    ID_REPORTE INT PRIMARY KEY IDENTITY(1,1),
    FECHA DATETIME,
    PROGRESO TEXT,
    ID_ARBOL INT,
    FOREIGN KEY (ID_ARBOL) REFERENCES ARBOL(ID_ARBOL)
);

-- Tabla Servicios
CREATE TABLE SERVICIOS (
    ID_SERVICIO INT PRIMARY KEY IDENTITY(1,1),
    TIPO VARCHAR(50)
);

CREATE TABLE GENERA(
	ID_GENERA INT PRIMARY KEY IDENTITY(1,1),
	ID_US INT,
	ID_REPORTE INT,
	FOREIGN KEY(ID_US) REFERENCES ADMINISTRADOR(ID_US),
	FOREIGN KEY(ID_REPORTE) REFERENCES REPORTES(ID_REPORTE)
)

-- Tabla Brindan
CREATE TABLE BRINDAN (
	ID_BRINDAN INT PRIMARY KEY IDENTITY(1,1),
    ID_ARBOL INT,
    ID_SERVICIO INT,
    FECHA_SERVICIO DATETIME,
	COMENTARIOS VARCHAR(500),
	ESTADO VARCHAR(100),
    FOREIGN KEY (ID_ARBOL) REFERENCES Arbol(ID_ARBOL),
    FOREIGN KEY (ID_SERVICIO) REFERENCES Servicios(ID_SERVICIO)
);

CREATE TABLE NOTIFICACIONES(
	ID_NOTIFICACION INT PRIMARY KEY IDENTITY(1,1),
	ID_US INT,
	ID_ARBOL INT,
	MENSAJE VARCHAR(255),
	FECHA_ENVIO DATETIME,
	LEIDO BIT DEFAULT 0
)
